

CHROMA: 
  host: "../data/chromadb"
  port: "8000"
  embedding_model: "../data/models/gte-large"
  embedding_device: "cpu"
  collection_name_documents: "documents"
  collection_name_cards: "cards"

cards_folder: "data/etl/processed/cards"
documents_folder: "data/etl/processed/documents"